version: '3'
services:
  vue-app:
    build: .
    ports:
      - '3217:80'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - vue-build

  vue-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run build
