# Используем официальный Node.js образ в качестве базового
FROM node:16-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json в рабочую директорию
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта в рабочую директорию
COPY . .

# Сборка приложения
RUN npm run build

# Используем nginx для сервировки скомпилированного приложения
FROM nginx:alpine

# Копируем скомпилированные файлы из предыдущего шага в директорию, обслуживаемую nginx
COPY --from=0 /app/dist /usr/share/nginx/html

# Копируем конфигурационный файл nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Открываем порт 80 для доступа к приложению
EXPOSE 80

# Запуск nginx
CMD ["nginx", "-g", "daemon off;"]
